game:
  round_time: 60
  round_count: 30
  start_time: 2019-04-18 15:47:00+03:00 
  checkers_path: checkers/

celery:
  broker_url: redis://redis:6379/1
  backend_url: redis://redis:6379/1
  task_serializer: json
  accept_content:
    - json
  result_serializer: json
  broker_transport_options:
    visibility_timeout: 36000

  worker_prefetch_multiplier: 1

  timezone: Europe/Moscow

flower:
  username: username
  password: password

db:
  postgres:
    host: postgres
    port: 5432
    user: dbuser
    password: dbpass
    name: test_db

team:
  - name: "Red team"
    type: "red"
    ip: null

  - name: "Blue team"
    type: "blue"
    ip: "95.179.181.235"

tasks:
  - name: notebook
    checker: notebook/checker.py 
    gets: 1
    puts: 1
    vulns: 1
    timeout: 10