game:
  round_time: 5
  round_count: 30
  start_time: 2020-04-18 15:47:00+03:00 
  checkers_path: /checkers/

celery:
  broker_url: redis://redis:6379/1
  backend_url: redis://redis:6379/1
  task_serializer: json
  accept_content:
    - json
  result_serializer: json
  broker_transport_options:
    visibility_timeout: 36000

  worker_prefetch_multiplier: 1

  timezone: Europe/Moscow

flower:
  username: username
  password: password

db:
  postgres:
    host: 192.168.99.107
    port: 5432
    user: roma
    password: xyecoc
    name: test_db

team:
  - name: "Red team"
    type: "red"
    ip: null

  - name: "Blue team"
    type: "blue"
    ip: "192.168.1.3"

tasks:
  - name: Test task
    checker: awesomeBlog/check.py 
    gets: 1
    puts: 1